on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:
    inputs:
      simple-icons-version:
        type: number
        description: Simple Icons major version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git Credentials
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@noreply.github.com

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6
          enable-cache: false

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Generate Source Files
        id: generate
        run: uv run generate.py
        env:
          SIMPLE_ICONS_VERSION: ${{ inputs.simple-icons-version }}

      - name: Bump Version
        run: npm version --force ${{ steps.generate.outputs.si-version }}

      - name: Publish Package
        run: bunx can-npm-publish && bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

