name: Publish Package

on:
  #  schedule:
  #    - cron: 0 0 * * *

  workflow_dispatch:
    inputs:
      simple-icons-version:
        type: number
        description: Simple Icons major version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6
          enable-cache: false

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: https://npm.pkg.github.com

      - name: Install RPK
        run: uv sync

      - name: Generate Workspaces
        run: uv run rpk gen base all

      - name: Install Dependencies
        run: bun install

      - name: Build Packages
        run: bun turbo build

      - name: Publish Packages
        run: bun turbo publish
        env:
          SIMPLE_ICONS_VERSION: ${{ inputs.simple-icons-version }}
#          NODE_OPTIONS: --max_old_space_size=8192