name: Publish Package

on:
  #  schedule:
  #    - cron: 0 0 * * *

  workflow_dispatch:
    inputs:
      simple-icons-version:
        type: number
        description: Simple Icons major version


permissions:
  contents: read
  packages: write

jobs:
#  prepare:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Set Up uv
#        uses: astral-sh/setup-uv@v5
#        with:
#          version: 0.6
#          enable-cache: false
#
#      - name: Set Up Bun
#        uses: oven-sh/setup-bun@v2
#        with:
#          registry-url: https://npm.pkg.github.com
#
#      - name: Install RPK
#        run: uv sync
#
#      - name: Generate Workspaces
#        run: uv run rpk gen base all
#
#      - name: Install Dependencies
#        run: bun install
#
#      - name: Get Package Matrix
#        id: matrix
#        run: |
#          publish="$(bun turbo publish --dry=json | jq .packages)" >> ${GITHUB_OUTPUT}
#    outputs:
#      publish: ${{ steps.matrix.outputs.publish }}

  build:
    runs-on: ubuntu-latest
#    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        package: [
          "@celsiusnarhwal/ril-simple-icons",
          "@celsiusnarhwal/ril-bootstrap-icons",
          "@celsiusnarhwal/ril-material-symbols-100",
          "@celsiusnarhwal/ril-material-symbols-200",
          "@celsiusnarhwal/ril-material-symbols-300",
          "@celsiusnarhwal/ril-material-symbols-400",
          "@celsiusnarhwal/ril-material-symbols-500",
          "@celsiusnarhwal/ril-material-symbols-600",
          "@celsiusnarhwal/ril-material-symbols-700"
        ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6
          enable-cache: false

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com

      - name: Install RPK
        run: uv sync

      - name: Generate Workspaces
        run: uv run rpk gen base all

      - name: Install Dependencies
        run: bun install

      - name: Build Package
        run: bun turbo build --filter @celsiusnarhwal/ril-packages-common --filter=${{ matrix.package }}
        env:
          NODE_OPTIONS: --max_old_space_size=8192

      - name: Publish Packages
        run: bun turbo publish --filter=${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
          SIMPLE_ICONS_VERSION: ${{ inputs.simple-icons-version }}
